#!/usr/bin/env python3
"""
generate_marca_std.py — C.2
Reads brand_crosswalk.yaml and emits:
  1. A CASE WHEN SQL snippet for MARCA_STD (stdout)
  2. A file: configs/marca_std_case_when.sql

Usage:
    python3 scripts/generate_marca_std.py
"""

import yaml
import os

CROSSWALK_PATH = "configs/brand_crosswalk.yaml"
OUTPUT_PATH    = "configs/marca_std_case_when.sql"

def escape_sql(s):
    return s.replace("'", "''")

def build_case_when(crosswalk):
    lines = []
    lines.append("CASE")

    sections = ["danone_brands", "competitor_brands", "special_mappings"]
    for section in sections:
        brands = crosswalk.get(section, {})
        for canonical, info in brands.items():
            variants = info.get("variants", [])
            if not variants:
                continue
            # Build IN list
            escaped = [f"'{escape_sql(v.upper())}'" for v in variants]
            # Also add the canonical itself (TRIM UPPER) if not already in variants
            canonical_upper = f"'{escape_sql(canonical.upper())}'"
            if canonical_upper not in escaped:
                escaped.insert(0, canonical_upper)
            in_list = ", ".join(escaped)
            lines.append(f"    WHEN TRIM(UPPER(MARCA)) IN ({in_list})")
            lines.append(f"        THEN '{escape_sql(canonical)}'")

    lines.append("    ELSE TRIM(UPPER(MARCA))")
    lines.append("END AS MARCA_STD")
    return "\n".join(lines)

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root  = os.path.dirname(script_dir)

    with open(os.path.join(repo_root, CROSSWALK_PATH)) as f:
        crosswalk = yaml.safe_load(f)

    sql = build_case_when(crosswalk)

    out_path = os.path.join(repo_root, OUTPUT_PATH)
    with open(out_path, "w") as f:
        f.write("-- AUTO-GENERATED by scripts/generate_marca_std.py\n")
        f.write("-- Source: configs/brand_crosswalk.yaml\n")
        f.write("-- Add this CASE WHEN block to any layout SQL to produce MARCA_STD\n\n")
        f.write(sql)
        f.write("\n")

    print(f"✓ CASE WHEN written to {OUTPUT_PATH}")
    print(f"\n--- Preview (first 30 lines) ---")
    for line in sql.split("\n")[:30]:
        print(line)

if __name__ == "__main__":
    main()
